# Generated by Django 2.1 on 2018-03-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMemberships',
            fields=[
                ('membershipid', models.IntegerField(primary_key=True, serialize=False)),
                ('tier', models.IntegerField()),
            ],
            options={
                'db_table': 'club_memberships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRegisterPrivate',
            fields=[
                ('privatetitle', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('privateregnumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_register_private',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRegisterProgram',
            fields=[
                ('name', models.CharField(max_length=12)),
                ('programtitle', models.CharField(max_length=20)),
                ('programregnumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_register_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerReservesCourt',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('courtnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
            ],
            options={
                'db_table': 'customer_reserves_court',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('phonenumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('inssin', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'instructors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipPlans',
            fields=[
                ('tier', models.IntegerField(primary_key=True, serialize=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'membership_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeEmployees',
            fields=[
                ('officesin', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'office_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateCourseCourtReservation',
            fields=[
                ('privatetitle', models.CharField(max_length=20)),
                ('courtnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starttime', models.TextField()),
                ('endtime', models.TextField()),
            ],
            options={
                'db_table': 'private_course_court_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTaught',
            fields=[
                ('privatetitle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('private_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'private_taught',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramCourtReservation',
            fields=[
                ('courtnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TextField()),
                ('programtitle', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'program_court_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramTaught',
            fields=[
                ('programtitle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numberofpeople', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program_taught',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMembers',
            fields=[
                ('membershipid', models.ForeignKey(db_column='membershipid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenniscenter.ClubMemberships')),
                ('sid', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'student_members',
                'managed': False,
            },
        ),
    ]
